"""
Review Agent — 代码质量审查 + 通过/失败判定

职责:
  1. 读取生成的代码
  2. 结合执行结果判定是否通过
  3. 从 5 个维度打分: 功能、质量、安全、性能、可读性
  4. 输出结构化的审查报告

审查维度:
  - 功能正确性: 代码是否实现了目标功能
  - 代码质量: 命名、结构、类型注解、docstring
  - 安全性: SQL 注入、路径遍历、密钥硬编码
  - 性能: 明显的性能问题（N+1 查询等）
  - 可读性: 注释、命名清晰度、代码组织
"""

import json
import logging

from langchain_core.language_models import BaseChatModel
from langchain_core.tools import BaseTool

from app.agents.base import AgentBase

logger = logging.getLogger(__name__)


REVIEWER_SYSTEM_PROMPT = """You are a Senior Code Reviewer. Your job is to review code generated by an AI coding agent and decide if it passes quality standards.

## Review Dimensions (score each 0-100)

1. **Functionality** (功能正确性): Does the code do what the step requires?
2. **Code Quality** (代码质量): Type hints, docstrings, proper structure, PEP 8?
3. **Security** (安全性): No hardcoded secrets, no injection risks, input validated?
4. **Performance** (性能): No obvious N+1 queries, inefficient loops, or memory leaks?
5. **Readability** (可读性): Clear naming, good comments, logical organization?

## Pass Criteria
- All dimensions must score >= 60
- Average score must be >= 70
- No CRITICAL security issues

## Output Format (STRICT JSON — no markdown, no text outside JSON)

{
  "passed": true,
  "overall_score": 85,
  "dimensions": {
    "functionality": {"score": 90, "comment": "All requirements implemented correctly"},
    "code_quality": {"score": 85, "comment": "Well-structured with type hints"},
    "security": {"score": 80, "comment": "No hardcoded secrets, uses env vars"},
    "performance": {"score": 85, "comment": "Efficient implementation"},
    "readability": {"score": 85, "comment": "Clear naming and good comments"}
  },
  "critical_issues": [],
  "suggestions": [
    "Consider adding input validation for edge cases",
    "Add more descriptive error messages"
  ],
  "summary": "Code is well-written and meets all requirements. Minor suggestions for improvement."
}

## Important
- Output ONLY the JSON object.
- Do NOT wrap in markdown code blocks.
- Be honest but constructive — if code is bad, say so clearly.
"""


class ReviewAgent(AgentBase):
    """代码审查 Agent — 多维度质量评估"""

    name: str = "reviewer"

    def __init__(self, llm, tools=None, verbose=False):
        super().__init__(llm=llm, tools=tools, verbose=verbose)

    @property
    def system_prompt(self) -> str:
        return REVIEWER_SYSTEM_PROMPT

    def review(
        self,
        step_description: str,
        expected_output: str,
        code: str,
        execution_result: str = "",
    ) -> dict:
        """
        审查代码

        Args:
            step_description: 当前步骤描述
            expected_output: 预期产出（来自 Planner）
            code: 生成的代码内容（可能聚合了多个文件）
            execution_result: Docker 执行结果（如果有）

        Returns:
            dict: 结构化审查报告
        """
        prompt = f"""## Step Description
{step_description}

## Expected Output
{expected_output or 'Not specified'}

## Generated Code
```
{code[:5000]}
```
{"... (truncated)" if len(code) > 5000 else ""}

## Execution Result
{execution_result or '(code was not executed)'}

## Instructions
Review the code above against the step requirements and execution result.
Output your structured review as JSON.
"""

        logger.info(f"[Reviewer] Reviewing code ({len(code)} chars)")

        raw_response = self.invoke(prompt)

        # 解析 JSON
        from app.agents.planner import _extract_json

        review_json = _extract_json(raw_response)

        try:
            review = json.loads(review_json)
        except json.JSONDecodeError:
            logger.error(f"[Reviewer] Failed to parse review JSON")
            return {
                "passed": False,
                "overall_score": 0,
                "dimensions": {},
                "critical_issues": ["Reviewer failed to produce valid JSON"],
                "suggestions": [],
                "summary": f"Raw output: {raw_response[:500]}",
            }

        # 确保必要字段存在
        review.setdefault("passed", False)
        review.setdefault("overall_score", 0)
        review.setdefault("dimensions", {})
        review.setdefault("critical_issues", [])
        review.setdefault("suggestions", [])
        review.setdefault("summary", "No summary provided")

        if review["passed"]:
            logger.info(f"[Reviewer] PASSED — score: {review['overall_score']}/100")
        else:
            logger.warning(
                f"[Reviewer] FAILED — score: {review['overall_score']}/100, "
                f"issues: {len(review['critical_issues'])}"
            )

        return review
